sudo: required
services:
 - docker

before_install:
 - docker build -t devtest -f Dockerfile.dev .
 
 
script:
 - docker run devtest npm run test -- --coverage

deploy:
 provider: elasticbeanstalk
 region: "eu-west-2"
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-eu-west-2-688717546506"
 bucket_path: "docker-react"
 on:
  branch: master
 access_key: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"
